<?php
$Mlist = $_POST['mediaTlist'];
$Dlist = $_POST['dataTlist'];
$Mcounter = 0;
$Dcounter = 0;
$matchcount= 0;
$MA = explode(":",$Mlist);
$DA = explode(":",$Dlist);

$fp ="";
$space=' ';
$nomatch=0;
foreach ($MA as $mediaref){
	if($mediaref == ""){
		continue;
	}
	//$fullset .= $dataref;
	for ($i=0;$i<count($DA);$i++){
		if($DA[$i] == ""){
			continue;
		}
		
		$medEntry =explode("\t", $mediaref);
		
		
		if (strstr($medEntry[0],$DA[$i])){
		$inset .= $medEntry[1]."<br>";
			$matchcount++;
		}else{
		$notMatch++;
		}
	}
	
}
	//$fp .= $pathN[1]."</br>";
	
	$Dcounter = count($DA);
	$Mcounter = count($MA);
	$fullsetL = "<div id=\"FL\">$fullset</div>";
	$insetL = "<div id=\"IL\">$inset</div>";

print "$Mcounter entries in Media Table</br> $Dcounter entries in Data lists</br>$matchcount entries matched </br>list of entries in Media Table</br>$notMatch didnt match</br>$fullsetL</br>$insetL";

/*
style=    position: absolute;
    border: 1px black solid;
    top: 22%;
    left: 251px;
}
$listOfMediaRefs=(
"reg1.jpg	/var/www/html/ibis/Data/Images/reg1.jpg:",
"veg1.png	/var/www/html/ibis/Data/Images/veg1.png:",
"veg2.png	/var/www/html/ibis/Data/Images/veg2.png:",
"veg3.png	/var/www/html/ibis/Data/Images/veg3.png:",
"veg4.png	/var/www/html/ibis/Data/Images/veg4.png:",
"min1.jpg	/var/www/html/ibis/Data/Images/min1.jpg:",
"min2.jpg	/var/www/html/ibis/Data/Images/min2.jpg:",
"min3.jpg	/var/www/html/ibis/Data/Images/min3.jpg:",
"min4.jpg	/var/www/html/ibis/Data/Images/min4.jpg:",
"min5.jpg	/var/www/html/ibis/Data/Images/min5.jpg:",
"veg5.png	/var/www/html/ibis/Data/Images/veg5.png:",
"veg6.png	/var/www/html/ibis/Data/Images/veg6.png:",
"veg7.png	/var/www/html/ibis/Data/Images/veg7.png:",
"veg8.png	/var/www/html/ibis/Data/Images/veg8.png:",
"veg9.png	/var/www/html/ibis/Data/Images/veg9.png:",
"veg10.png	/var/www/html/ibis/Data/Images/veg10.png:",
"reg2.jpg	/var/www/html/ibis/Data/Images/reg2.jpg:",
"veg11.png	/var/www/html/ibis/Data/Images/veg11.png:",
"veg12.png	/var/www/html/ibis/Data/Images/veg12.png:",
"veg13.png	/var/www/html/ibis/Data/Images/veg13.png:",
"veg15.png	/var/www/html/ibis/Data/Images/veg15.png:",
"veg16.png	/var/www/html/ibis/Data/Images/veg16.png:",
"veg16.png	/var/www/html/ibis/Data/Images/veg16.png:",
"veg17.png	/var/www/html/ibis/Data/Images/veg17.png:",
"veg18.png	/var/www/html/ibis/Data/Images/veg18.png:",
"veg19.png	/var/www/html/ibis/Data/Images/veg19.png:",
"veg20.png	/var/www/html/ibis/Data/Images/veg20.png:",
"veg21.png	/var/www/html/ibis/Data/Images/veg21.png:",
"veg22.png	/var/www/html/ibis/Data/Images/veg22.png:",
"veg23.png	/var/www/html/ibis/Data/Images/veg23.png:",
"veg24.png	/var/www/html/ibis/Data/Images/veg24.png:",
"veg25.jpg	/var/www/html/ibis/Data/Images/veg25.jpg:",
"veg26.png	/var/www/html/ibis/Data/Images/veg26.png:",
"veg27.png	/var/www/html/ibis/Data/Images/veg27.png:",
"veg28.png	/var/www/html/ibis/Data/Images/veg28.png:",
"veg29.png	/var/www/html/ibis/Data/Images/veg29.png:",
"veg30.png	/var/www/html/ibis/Data/Images/veg30.png:",
"veg31.png	/var/www/html/ibis/Data/Images/veg31.png:",
"veg32.png	/var/www/html/ibis/Data/Images/veg32.png:",
"veg33.png	/var/www/html/ibis/Data/Images/veg33.png:",
"veg34.png	/var/www/html/ibis/Data/Images/veg34.png:",
"veg35.png	/var/www/html/ibis/Data/Images/veg35.png:",
"veg36.png	/var/www/html/ibis/Data/Images/veg36.png:",
"veg37.png	/var/www/html/ibis/Data/Images/veg37.png:",
"veg38.png	/var/www/html/ibis/Data/Images/veg38.png:",
"veg39.png	/var/www/html/ibis/Data/Images/veg39.png:",
"veg40.png	/var/www/html/ibis/Data/Images/veg40.png:",
"veg41.png	/var/www/html/ibis/Data/Images/veg41.png:",
"veg42.png	/var/www/html/ibis/Data/Images/veg42.png:",
"veg43.png	/var/www/html/ibis/Data/Images/veg43.png:",
"veg44.png	/var/www/html/ibis/Data/Images/veg44.png:",
"veg45.png	/var/www/html/ibis/Data/Images/veg45.png:",
"veg46.png	/var/www/html/ibis/Data/Images/veg46.png:",
"veg47.png	/var/www/html/ibis/Data/Images/veg47.png:",
"veg48.png	/var/www/html/ibis/Data/Images/veg48.png:",
"veg49.png	/var/www/html/ibis/Data/Images/veg49.png:",
"veg50.png	/var/www/html/ibis/Data/Images/veg50.png:",
"veg51.jpg	/var/www/html/ibis/Data/Images/veg51.jpg:",
"veg52.png	/var/www/html/ibis/Data/Images/veg52.png:",
"veg53.png	/var/www/html/ibis/Data/Images/veg53.png:",
"veg54.png	/var/www/html/ibis/Data/Images/veg54.png:",
"veg55.png	/var/www/html/ibis/Data/Images/veg55.png:",
"veg56.jpg	/var/www/html/ibis/Data/Images/veg56.jpg:",
"veg57.png	/var/www/html/ibis/Data/Images/veg57.png:",
"veg58.png	/var/www/html/ibis/Data/Images/veg58.png:",
"veg59.png	/var/www/html/ibis/Data/Images/veg59.png:",
"veg60.png	/var/www/html/ibis/Data/Images/veg60.png:",
"veg61.jpg	/var/www/html/ibis/Data/Images/veg61.jpg:",
"veg62.png	/var/www/html/ibis/Data/Images/veg62.png:",
"veg63.png	/var/www/html/ibis/Data/Images/veg63.png:",
"veg64.png	/var/www/html/ibis/Data/Images/veg64.png:",
"veg65.png	/var/www/html/ibis/Data/Images/veg65.png:",
"veg66.png	/var/www/html/ibis/Data/Images/veg66.png:",
"veg67.png	/var/www/html/ibis/Data/Images/veg67.png:",
"veg68.png	/var/www/html/ibis/Data/Images/veg68.png:",
"veg69.png	/var/www/html/ibis/Data/Images/veg69.png:",
"veg70.png	/var/www/html/ibis/Data/Images/veg70.png:",
"veg71.png	/var/www/html/ibis/Data/Images/veg71.png:",
"veg72.png	/var/www/html/ibis/Data/Images/veg72.png:",
"veg73.png	/var/www/html/ibis/Data/Images/veg73.png:",
"veg74.png	/var/www/html/ibis/Data/Images/veg74.png:",
"veg75.png	/var/www/html/ibis/Data/Images/veg75.png:",
"veg76.png	/var/www/html/ibis/Data/Images/veg76.png:",
"veg77.png	/var/www/html/ibis/Data/Images/veg77.png:",
"veg78.png	/var/www/html/ibis/Data/Images/veg78.png:",
"veg79.png	/var/www/html/ibis/Data/Images/veg79.png:",
"veg80.png	/var/www/html/ibis/Data/Images/veg80.png:",
"veg81.png	/var/www/html/ibis/Data/Images/veg81.png:",
"veg82.png	/var/www/html/ibis/Data/Images/veg82.png:",
"veg83.png	/var/www/html/ibis/Data/Images/veg83.png:",
"veg84.png	/var/www/html/ibis/Data/Images/veg84.png:",
"veg85.png	/var/www/html/ibis/Data/Images/veg85.png:",
"veg86.png	/var/www/html/ibis/Data/Images/veg86.png:",
"veg87.png	/var/www/html/ibis/Data/Images/veg87.png:",
"veg88.png	/var/www/html/ibis/Data/Images/veg88.png:",
"veg89.png	/var/www/html/ibis/Data/Images/veg89.png:",
"veg90.png	/var/www/html/ibis/Data/Images/veg90.png:",
"veg91.png	/var/www/html/ibis/Data/Images/veg91.png:",
"veg92.png	/var/www/html/ibis/Data/Images/veg92.png:",
"veg93.png	/var/www/html/ibis/Data/Images/veg93.png:",
"veg94.png	/var/www/html/ibis/Data/Images/veg94.png:",
"veg95.png	/var/www/html/ibis/Data/Images/veg95.png:",
"veg96.png	/var/www/html/ibis/Data/Images/veg96.png:",
"veg97.png	/var/www/html/ibis/Data/Images/veg97.png:",
"veg98.png	/var/www/html/ibis/Data/Images/veg98.png:",
"veg99.png	/var/www/html/ibis/Data/Images/veg99.png:",
"veg100.png	/var/www/html/ibis/Data/Images/veg100.png:",
"veg101.png	/var/www/html/ibis/Data/Images/veg101.png:",
"veg102.png	/var/www/html/ibis/Data/Images/veg102.png:",
"veg103.png	/var/www/html/ibis/Data/Images/veg103.png:",
"veg104.png	/var/www/html/ibis/Data/Images/veg104.png:",
"veg105.png	/var/www/html/ibis/Data/Images/veg105.png:",
"veg106.png	/var/www/html/ibis/Data/Images/veg106.png:",
"veg107.png	/var/www/html/ibis/Data/Images/veg107.png:",
"veg108.jpg	/var/www/html/ibis/Data/Images/veg108.jpg:",
"min6.png	/var/www/html/ibis/Data/Images/min6.png:",
"min7.png	/var/www/html/ibis/Data/Images/min7.png:",
"min8.png	/var/www/html/ibis/Data/Images/min8.png:",
"min9.png	/var/www/html/ibis/Data/Images/min9.png:",
"veg109.png	/var/www/html/ibis/Data/Images/veg109.png:",
"veg110.jpg	/var/www/html/ibis/Data/Images/veg110.jpg:",
"veg111.jpg	/var/www/html/ibis/Data/Images/veg111.jpg:",
"guest1.jpg	/var/www/html/ibis/Data/Images/guest1.jpg:",
"guest2.jpg	/var/www/html/ibis/Data/Images/guest2.jpg:",
"guest3.jpg	/var/www/html/ibis/Data/Images/guest3.jpg:",
"guest4.jpg	/var/www/html/ibis/Data/Images/guest4.jpg:",
"veg112.png	/var/www/html/ibis/Data/Images/veg112.png:",
"veg113.png	/var/www/html/ibis/Data/Images/veg113.png:",
"veg114.png	/var/www/html/ibis/Data/Images/veg114.png:",
"veg115.png	/var/www/html/ibis/Data/Images/veg115.png:",
"reg3.jpg	/var/www/html/ibis/Data/Images/reg3.jpg:",
"veg116.jpg	/var/www/html/ibis/Data/Images/veg116.jpg:",
"reg4.png	/var/www/html/ibis/Data/Images/reg4.png:",
"reg5.jpg	/var/www/html/ibis/Data/Images/reg5.jpg:",
"guest5.jpg	/var/www/html/ibis/Data/Images/guest5.jpg:",
"veg117.png	/var/www/html/ibis/Data/Images/veg117.png:",
"veg118.png	/var/www/html/ibis/Data/Images/veg118.png:",
"veg119.png	/var/www/html/ibis/Data/Images/veg119.png:",
"min10.jpg	/var/www/html/ibis/Data/Images/min10.jpg:",
"min11.jpg	/var/www/html/ibis/Data/Images/min11.jpg:",
"guest6.jpg	/var/www/html/ibis/Data/Images/guest6.jpg:",
"guest7.gif	/var/www/html/ibis/Data/Images/guest7.gif:",
"guest8.jpg	/var/www/html/ibis/Data/Images/guest8.jpg:",
"guest9.jpg	/var/www/html/ibis/Data/Images/guest9.jpg:",
"reg6.jpg	/var/www/html/ibis/Data/Images/reg6.jpg:",
"guest10.jpg	/var/www/html/ibis/Data/Images/guest10.jpg:",
"veg120.jpg	/var/www/html/ibis/Data/Images/veg120.jpg:",
"veg121.jpg	/var/www/html/ibis/Data/Images/veg121.jpg:",
"veg122.jpg	/var/www/html/ibis/Data/Images/veg122.jpg:",
"veg123.jpg	/var/www/html/ibis/Data/Images/veg123.jpg:",
"veg124.jpg	/var/www/html/ibis/Data/Images/veg124.jpg:",
"veg125.jpg	/var/www/html/ibis/Data/Images/veg125.jpg:",
"veg126.jpg	/var/www/html/ibis/Data/Images/veg126.jpg:",
"veg127.jpg	/var/www/html/ibis/Data/Images/veg127.jpg:",
"guest11.jpg	/var/www/html/ibis/Data/Images/guest11.jpg:",
"reg7.jpg	/ibis/Data/Images/reg7.jpg:",
"guest12jpeg	/var/www/html/ibis/Data/Images/guest12jpeg:",
"veg128.jpg	/var/www/html/ibis/Data/Images/veg128.jpg:",
"veg129jpeg	/var/www/html/ibis/Data/Images/veg129jpeg:",
"anim1.jpg	/var/www/html/ibis/Data/Images/anim1.jpg:",
"anim2.jpg	/var/www/html/ibis/Data/Images/anim2.jpg:",
"anim3.jpg	/var/www/html/ibis/Data/Images/anim3.jpg:",
"anim4.jpg	/var/www/html/ibis/Data/Images/anim4.jpg:",
"anim5.jpg	/var/www/html/ibis/Data/Images/anim5.jpg:",
"anim6.jpg	/var/www/html/ibis/Data/Images/anim6.jpg:",
"anim7.jpg	/var/www/html/ibis/Data/Images/anim7.jpg:",
"anim8.jpg	/var/www/html/ibis/Data/Images/anim8.jpg:",
"anim9.jpg	/var/www/html/ibis/Data/Images/anim9.jpg:",
"anim10.jpg	/var/www/html/ibis/Data/Images/anim10.jpg:",
"anim11.jpg	/var/www/html/ibis/Data/Images/anim11.jpg:",
"anim12.jpg	/var/www/html/ibis/Data/Images/anim12.jpg:",
"anim13.jpg	/var/www/html/ibis/Data/Images/anim13.jpg:",
"anim14.jpg	/var/www/html/ibis/Data/Images/anim14.jpg:",
"anim15.jpg	/var/www/html/ibis/Data/Images/anim15.jpg:",
"anim16.jpg	/var/www/html/ibis/Data/Images/anim16.jpg:",
"anim17.jpg	/var/www/html/ibis/Data/Images/anim17.jpg:",
"anim18.jpg	/var/www/html/ibis/Data/Images/anim18.jpg:",
"anim19.jpg	/var/www/html/ibis/Data/Images/anim19.jpg:",
"anim20.jpg	/var/www/html/ibis/Data/Images/anim20.jpg:",
"veg130.png	/var/www/html/ibis/Data/Images/veg130.png:",
"anim21.jpg	/var/www/html/ibis/Data/Images/anim21.jpg:",
"anim22.jpg	/var/www/html/ibis/Data/Images/anim22.jpg:",
"anim23.jpg	/var/www/html/ibis/Data/Images/anim23.jpg:",
"anim24.jpg	/var/www/html/ibis/Data/Images/anim24.jpg:",
"anim25.jpg	/var/www/html/ibis/Data/Images/anim25.jpg:",
"anim26.png	/var/www/html/ibis/Data/Images/anim26.png:",
"anim27.png	/var/www/html/ibis/Data/Images/anim27.png:",
"anim28.png	/var/www/html/ibis/Data/Images/anim28.png:",
"anim29.png	/var/www/html/ibis/Data/Images/anim29.png:",
"anim30.png	/var/www/html/ibis/Data/Images/anim30.png:",
"anim31.png	/var/www/html/ibis/Data/Images/anim31.png:",
"anim32.png	/var/www/html/ibis/Data/Images/anim32.png:",
"anim33.png	/var/www/html/ibis/Data/Images/anim33.png:",
"anim34.png	/var/www/html/ibis/Data/Images/anim34.png:",
"anim35.png	/var/www/html/ibis/Data/Images/anim35.png:",
"anim36.png	/var/www/html/ibis/Data/Images/anim36.png:",
"anim37.png	/var/www/html/ibis/Data/Images/anim37.png:",
"anim38.png	/var/www/html/ibis/Data/Images/anim38.png:",
"anim39.png	/var/www/html/ibis/Data/Images/anim39.png:",
"anim40.png	/var/www/html/ibis/Data/Images/anim40.png:",
"anim41.png	/var/www/html/ibis/Data/Images/anim41.png:",
"veg131.png	/var/www/html/ibis/Data/Images/veg131.png:",
"veg132.png	/var/www/html/ibis/Data/Images/veg132.png:",
"veg133.png	/var/www/html/ibis/Data/Images/veg133.png:",
"veg134.png	/var/www/html/ibis/Data/Images/veg134.png:",
"veg135.png	/var/www/html/ibis/Data/Images/veg135.png:",
"veg136.png	/var/www/html/ibis/Data/Images/veg136.png:",
"veg137.png	/var/www/html/ibis/Data/Images/veg137.png:",
"veg138.png	/var/www/html/ibis/Data/Images/veg138.png:",
"veg139.png	/var/www/html/ibis/Data/Images/veg139.png:",
"veg140.jpg	/var/www/html/ibis/Data/Images/veg140.jpg:",
"veg141.png	/var/www/html/ibis/Data/Images/veg141.png:",
"veg142.png	/var/www/html/ibis/Data/Images/veg142.png:",
"veg143.png	/var/www/html/ibis/Data/Images/veg143.png:",
"veg144.jpg	/var/www/html/ibis/Data/Images/veg144.jpg:",
"veg145.png	/var/www/html/ibis/Data/Images/veg145.png:",
"veg146.png	/var/www/html/ibis/Data/Images/veg146.png:",
"veg147.png	/var/www/html/ibis/Data/Images/veg147.png:",
"veg148.png	/var/www/html/ibis/Data/Images/veg148.png:",
"veg149.jpg	/var/www/html/ibis/Data/Images/veg149.jpg:",
"veg150.png	/var/www/html/ibis/Data/Images/veg150.png:",
"veg151.png	/var/www/html/ibis/Data/Images/veg151.png:",
"veg152.png	/var/www/html/ibis/Data/Images/veg152.png:",
"veg153.jpg	/var/www/html/ibis/Data/Images/veg153.jpg:",
"veg154.png	/var/www/html/ibis/Data/Images/veg154.png:",
"veg155.png	/var/www/html/ibis/Data/Images/veg155.png:",
"veg156.jpg	/var/www/html/ibis/Data/Images/veg156.jpg:",
"veg157.jpg	/var/www/html/ibis/Data/Images/veg157.jpg:",
"veg158.png	/var/www/html/ibis/Data/Images/veg158.png:",
"veg159.png	/var/www/html/ibis/Data/Images/veg159.png:",
"veg160.jpg	/var/www/html/ibis/Data/Images/veg160.jpg:",
"veg161.jpg	/var/www/html/ibis/Data/Images/veg161.jpg:",
"veg162.jpg	/var/www/html/ibis/Data/Images/veg162.jpg:",
"veg163.png	/var/www/html/ibis/Data/Images/veg163.png:",
"veg164.png	/var/www/html/ibis/Data/Images/veg164.png:",
"veg165.png	/var/www/html/ibis/Data/Images/veg165.png:",
"veg166.png	/var/www/html/ibis/Data/Images/veg166.png:",
"veg167.png	/var/www/html/ibis/Data/Images/veg167.png:",
"veg168.png	/var/www/html/ibis/Data/Images/veg168.png:",
"veg169.png	/var/www/html/ibis/Data/Images/veg169.png:",
"veg170.png	/var/www/html/ibis/Data/Images/veg170.png:",
"veg171.jpg	/var/www/html/ibis/Data/Images/veg171.jpg:",
"veg172.jpg	/var/www/html/ibis/Data/Images/veg172.jpg:",
"veg173.png	/var/www/html/ibis/Data/Images/veg173.png:",
"min12.png	/var/www/html/ibis/Data/Images/min12.png:",
"reg8.jpg	/ibis/Data/Images/reg8.jpg:",
"anim42.jpg	/var/www/html/ibis/Data/Images/anim42.jpg:",
"anim43.jpg	/var/www/html/ibis/Data/Images/anim43.jpg:",
);
*/
?>
