<?php
	$family = "family";
	$genus = "genus";
	$species = "species";
	$local_names = "local_names";
	$media_references = "media_references";
	$name = "name";
	$group = "Mgroup";
	$chemical_formula = "chemical_formula";
	$firstEntryList = array();
	$thehfileList = array();
	$guest_acc = "johnGalt";
	$guest_pass = "ibisguest01";
	$contrib_acc = "Contributer";
	$contrib_pass = "IBIScontrib01";
	$editor_acc = "Editor";
	$editor_pass = "IBISeditor01";
	$uploaddir = "/var/www/html/ibis/Data/Images/";
	$imagesfroot = "/var/www/html/IBIS_Files_new/Data/Images/";
	$imagesdroot = "/var/www/IBIS_Files_new/Data/Images/"; 
	$imagesNotebookroot ="/var/www/html/ibis/Data/Images/";  
	$imageshroot = "/ibis/Data/Images/";	 
	$serverRoot = "/ibis/Data/Images/";
	$space = " ";
	$underscore = "_";
?>
